<?php

namespace Hypersites\StockBundle\Entity;

use Hypersites\StockBundle\Entity\Item;
use Hypersites\StockBundle\Entity\ProductVariation;
/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function getPossibleForInternalUse(ProductVariation $productVariation) {
      $statusToInternalUse = array(
        Item::ON_STOCK,
        Item::RETURNED_BY_CUSTOMER,
      );
      $query = $this->createQueryBuilder("i")
              ->where("i.status IN(:status)")
              ->andWhere("i.productVariation = :productVariation")
              ->setParameter("status", $statusToInternalUse)
              ->setParameter("productVariation", $productVariation)
              ->getQuery();
      return $query->getResult();
    }
}
