<?php

namespace Hypersites\StockBundle\Entity;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll() {
        $baseQuery = "Select p from Product p";
        $query = $this->createQueryBuilder("p")
                ->setFirstResult(0)
                ->setMaxResults(15)
                ->getQuery();
        
                
        return $paginator = new \Doctrine\ORM\Tools\Pagination\Paginator($query);
    }
}
