<?php

namespace Hypersites\StockBundle\Entity;

/**
 * ProductVariationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductVariationRepository extends \Doctrine\ORM\EntityRepository
{
}
