<?php

namespace Hypersites\StockBundle\Entity;

/**
 * StockMovementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockMovementRepository extends \Doctrine\ORM\EntityRepository
{
}
