<?php

namespace Hypersites\StockBundle\Entity;

use Hypersites\StockBundle\Entity\Product;

/**
 * VariationAttributesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VariationAttributesRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPossibleVariationsForProduct(Product $product) 
    {
        $attributes = $product->getAttributes();
        
        
        
        
        $this->createQueryBuilder($alias);
    }
    
}
