<?php

namespace Hypersites\StockBundle\Entity;

/**
 * VariationAttributesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VariationAttributesRepository extends \Doctrine\ORM\EntityRepository
{
}
